### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by tbodt** [SimonSapin/html5ever-python#1]
The name html5ever has been reserved on pypi, apparently by @SimonSapin, but it has not yet been published.

**Comment by SimonSapin** [comment]
I don’t really intend to maintain this over time. If you’d like to take over, let me know your PyPI user name and I can give you access.

**Comment by tbodt** [comment]
If this isn't going to be maintained, maybe the C api included in this should be moved back into html5ever?

**Comment by SimonSapin** [comment]
html5ever used to have a C API in its own repository, but it was never complete or really working. Nobody cared enough to fix it, until it was removed. I’d be opposed to adding something back unless it has a lot more tests and actual users.

(Also the C API in this repository is made specifically with Python / CFFI in mind, and doesn’t necessarily work well for other uses.)

**Comment by tbodt** [comment]
I'm afraid I may be the only potential user of the C api...

I've already started writing my own set of Python bindings in Cython, so I can use lxml to build trees without touching Python land, so this won't be too useful to me. Oh well...

**Comment by SimonSapin** [comment]
That sounds interesting. IIRC with the code in this repo the majority of the parsing time was spent creating Python objects, so your approach could lead to better performance. Is your code available online? I’m curious to see it.

Again, if you’d like to use https://pypi.python.org/pypi/html5ever I’ll give it to you. Just give me your PyPI username.

**Comment by tbodt** [comment]
When it's at a reasonable state of completeness, I'll publish it at https://github.com/tbodt/htmlpyever.

**Comment by tbodt** [comment]
I'm using a copy of lib.rs from rust-glue, but it doesn't compile on the latest version of rust. This is partially because some things such as QualName and catch_panic have been renamed or moved, so I fixed that, but there's still some errors:

```
error: attempted tuple index `0` on type `string_cache::Atom<html5ever_atoms::NamespaceStaticSet>`, but the type was not a tuple or tuple struct
   --> src/glue.rs:127:38
    |
125 |               check_int(call!(self, add_attribute_if_missing(
    |  _______________________- starting here...
126 | |                 element,
127 | |                 Utf8Slice::from_str(&attribute.name.ns.0),
    | |                                      ^^^^^^^^^^^^^^^^^^^
128 | |                 Utf8Slice::from_str(&attribute.name.local),
129 | |                 Utf8Slice::from_str(&attribute.value))));
    | |_______________________________________________________- ...ending here: in this macro invocation

error: attempted tuple index `0` on type `string_cache::Atom<html5ever_atoms::NamespaceStaticSet>`, but the type was not a tuple or tuple struct
   --> src/glue.rs:167:50
    |
167 |         let namespace_url = Utf8Slice::from_str(&name.ns.0);
    |                                                  ^^^^^^^^^

error[E0277]: the trait bound `&mut html5ever::tokenizer::buffer_queue::BufferQueue: std::convert::From<&str>` is not satisfied
   --> src/glue.rs:375:42
    |
375 |         parser.tokenizer.feed((&*string).into())
    |                                          ^^^^ the trait `std::convert::From<&str>` is not implemented for `&mut html5ever::tokenizer::buffer_queue::BufferQueue`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<&mut html5ever::tokenizer::buffer_queue::BufferQueue>` for `&str`

error[E0308]: mismatched types
   --> src/glue.rs:375:9
    |
375 |         parser.tokenizer.feed((&*string).into())
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `html5ever::tokenizer::TokenizerResult`
    |
    = note: expected type `()`
    = note:    found type `html5ever::tokenizer::TokenizerResult<NodeHandle>`

error[E0277]: the trait bound `F: std::panic::UnwindSafe` is not satisfied
   --> src/glue.rs:403:5
    |
403 |     catch_unwind(f).ok()
    |     ^^^^^^^^^^^^ the trait `std::panic::UnwindSafe` is not implemented for `F`
    |
    = help: consider adding a `where F: std::panic::UnwindSafe` bound
    = note: required by `std::panic::catch_unwind`

error[E0277]: the trait bound `F: std::panic::UnwindSafe` is not satisfied
   --> src/glue.rs:407:11
    |
407 |     match catch_unwind(f) {
    |           ^^^^^^^^^^^^ the trait `std::panic::UnwindSafe` is not implemented for `F`
    |
    = help: consider adding a `where F: std::panic::UnwindSafe` bound
    = note: required by `std::panic::catch_unwind`

error: aborting due to 6 previous errors
```

I just started learning rust, so it may take a while for me to get all this fixed.

**Comment by tbodt** [comment]
Is there any good way to fix this, or should I just leave it? (I've replaced catch_panic with catch_unwind and Send with UnwindSafe.)

```rs
// FIXME: These make catch_unwind happy, but they are total lies as far as I know.
impl UnwindSafe for BytesSlice {}
impl UnwindSafe for ParserMutPtr {}
impl UnwindSafe for Parser {}
```

**Comment by SimonSapin** [comment]
Unwind safety (a.k.a panic-safety, exception-safety) is hard. I took this shortcut in order to get a prototype running without spending too much time figuring out if this is safe in every corner case. If you want to use this code in production, I recommend reading up on the subject:

https://doc.rust-lang.org/std/panic/fn.catch_unwind.html
https://doc.rust-lang.org/std/panic/trait.UnwindSafe.html
https://doc.rust-lang.org/nomicon/unwinding.html
https://doc.rust-lang.org/nomicon/exception-safety.html
https://doc.rust-lang.org/nomicon/poisoning.html

This probably looks overwhelming, I’m sorry about that. Unwind-safety is really a hard problem to solve, and it’s still somewhat the "early adopters" phase for Rust FFI :)

**Comment by tbodt** [comment]
I'm thinking that if the parser panics, I'll set a flag and return null, and any future calls to the parser will immediately return null, because the parser panicked and is now in an unknown state. Does that make any sense?

**Comment by SimonSapin** [comment]
Yes, I think this is the same as "poisoning". The Python wrapper code should probably raise a Python exception when that happens.

**Comment by tbodt** [comment]
https://github.com/tbodt/htmlpyever

Everything needed should be there, just `cargo build` and `./setup.py develop`. I'm still working on namespace support and sane panic handling.
