### ISSUE TITLE
Viability of Use

### ISSUE THREAD

**Issue by adamhammes** [SimonSapin/html5ever-python#2]
Are there any installation instructions for this library? I think it might be useful for a personal project.

I would also appreciate any links you have to documentation.

**Comment by SimonSapin** [comment]
There is no documentation. Viability is probably nil. This is an experiment that I made over two weekends a year and a half ago. I have no intention of maintaining it further. The code may or may not be useful to you, feel free to use it according to the license. If you do so, you’re probably better off copying it somewhere else than depending on this repository. You may also want to have a look at https://github.com/tbodt/htmlpyever (via #1).

**Comment by adamhammes** [comment]
Thank you so much for your response! I'll take a deeper look at it over break to see if I want to work on it.
