### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by LuoZijun** [SimonSapin/html5ever-python#3]
os     : macOS 10.12.5
rustc: rustc 1.18.0 (03fc9d622 2017-06-06)

The rust version 1.6.0 has `std::thread::catch_panic` function, 
but now is removed (stable && nightly).

import at: https://github.com/SimonSapin/html5ever-python/blob/master/rust-glue/lib.rs#L13

so, this lines looks must be rewrite.

https://github.com/SimonSapin/html5ever-python/blob/master/rust-glue/lib.rs#L399-L408

**Comment by SimonSapin** [comment]
This repository contains a hack that I made over a couple week-ends, a couple years ago. I do not maintain it. You may be interested in https://github.com/tbodt/htmlpyever.

**Comment by LuoZijun** [comment]
@SimonSapin Okay.
